[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
scrap_engine = "5wCGNL7Mo2FNpATH8PPfq37L4rJ25qbSfbhCXFhTEsAH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
